AWSTemplateFormatVersion: 2010-09-09
Description: Builds a deployer iam user and role

Parameters:
  StackPrefix:
    Type: String
  UserName:
    Type: String

Resources:
  DeployerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  DeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AWS::StackName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
              - sts:TagSession
            Principal:
              AWS:
                - !GetAtt [DeployerUser, Arn]

  DeployerUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sts:TagSession
              - sts:AssumeRole
            Resource: !GetAtt [DeployerRole, Arn]
      PolicyName: AllowToAssumeRoleAndTagSession
      Users:
        - !Ref DeployerUser

  DeployerRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - ec2:*
              - elasticloadbalancing:*
              - application-autoscaling:*
              - cloudwatch:*
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:*
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackPrefix}-fargate-default-task-role"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackPrefix}-fargate-default-task-execution-role"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackPrefix}-fargate-service-auto-scaling-role"
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/fargate/${StackPrefix}-fargate/dev:log-stream:"
          - Effect: Allow
            Action:
              - ecs:CreateCluster
              - ecs:DeleteCluster
              - ecs:ListClusters
              - ecs:DescribeClusters
              - ecs:RegisterTaskDefinition
              - ecs:DeregisterTaskDefinition
              - ecs:DescribeTaskDefinition
              - ecs:ListTaskDefinitions
            Resource: "*"
          - Effect: Allow
            Action:
              - ecs:*
            Resource:
              - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${StackPrefix}-fargate"
              - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${StackPrefix}-fargate/${StackPrefix}-fargate"
          - Effect: Allow
            Action:
              - ecr:*
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${StackPrefix}-ecr"
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${StackPrefix}-ecr/*"
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${StackPrefix}-vpc/*"
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${StackPrefix}-fargate/*"
      PolicyName: DeployerRoleCapabilities
      Roles:
        - !Ref DeployerRole

Outputs:
  DeployerUser:
    Value: !Ref DeployerUser
  DeployerRole:
    Value: !Ref DeployerRole
