AWSTemplateFormatVersion: 2010-09-09
Description: Builds a deployer iam user and role

Parameters:
  UserName:
    Type: String

Resources:
  DeployerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  DeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AWS::StackName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
              - sts:TagSession
            Principal:
              AWS:
                - !GetAtt [DeployerUser, Arn]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildReadOnlyAccess

  DeployerUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sts:TagSession
              - sts:AssumeRole
            Resource: !GetAtt [DeployerRole, Arn]
      PolicyName: AllowToAssumeRoleAndTagSession
      Users:
        - !Ref DeployerUser

  DeployerRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - ecr:*
            Resource:
              - !Join [
                  "",
                  [
                    "arn:aws:ecr:eu-central-1:",
                    !Ref AWS::AccountId,
                    ":repository/log-docker-ecr-",
                    !Ref AWS::AccountId,
                  ],
                ]
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource:
              - !Join [
                  "",
                  [
                    "arn:aws:cloudformation:eu-central-1:",
                    !Ref AWS::AccountId,
                    ":stack/log-docker-ecr/*",
                  ],
                ]
      PolicyName: DeployerRoleCapabilities
      Roles:
        - !Ref DeployerRole

Outputs:
  DeployerUser:
    Value: !Ref DeployerUser
  DeployerRole:
    Value: !Ref DeployerRole
