AWSTemplateFormatVersion: 2010-09-09
Description: Builds an ECR Repository

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        !Join ["-", [!Ref "AWS::StackName", !Ref "AWS::AccountId"]]
